channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.0
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - torch==2.6.0
  - tqdm==4.67.1
name: mlflow-env
